"""Every per-platform fact about an ATS board, as data: one TOML file per
platform in board_specs/ beside this module, `<name>.toml`, read once
at import.

`BOARDS[ats]` says how a store row names a board, how its listing is read
and mapped to rows, how one posting is read back, and how a posting's
closure is judged. The engine that reads it is `src.ats.board` (its
default the models in `src.ats.board.spec`, where each key's meaning and
default are declared); outside them, no module in `src/` names a platform
(tests/test_board_specs.py).

`_order.toml` lists every spec in detection order: an input two specs both
read goes to the earlier one, and only the pairs tests/test_board_specs.py
declares in `OVERLAPS` may overlap. A compiled build also reads
`DATA_DIR/boards/<name>.toml` (`OVERRIDE_DIR`), so a spec changes without a
rebuild: a file naming a bundled platform replaces its spec in place, any
other adds a platform after every bundled one. An override that does not
parse is skipped; one that fails the schema is refused by src.ats.board,
which keeps the bundled spec (`BUNDLED`). From source there are no
overrides: edit the files in board_specs/.

The specs hold only what JSON can, and no None (tests/test_invariants.py);
regexes are TOML literal strings ('...'), read as written. Two files beside
them in board_specs/ are generated by tools/board_catalog.py, never edited:
board-spec.schema.json, the JSON Schema an editor with the Tombi extension
completes and checks a spec against (tombi.toml; `tombi lint` in CI), and
README.md, the catalog (docs/board-spec-format.md).

Rules:

- A value every platform shares is an engine default
  (`src.ats.board.spec`), never repeated per spec. Decided 2026-10-08: no
  spec sets location's default (the engine's "" is the one unknown
  location, and `src.match.locality.location_unknown` also reads a literal
  "Unknown" as unknown); no spec sets `"department": None` (a listing
  alternative's `fields` replace the first's wholesale, and an absent key
  already reads None).
- A spec holds no logic of its own: a behaviour one platform needs is a
  grammar change in the engine (`src.ats.board`), declared in its schema,
  so every spec can use it.
- Each kind of rationale has one home. A line-level comment explains one
  value, on the line above it. A workaround key carries its `why`.
  Reasoning about a whole platform (canary choice, tenant quirks, dated
  incidents) goes in the file's header comment, under `Notes:` for
  history.

The host lists below are derived from the specs' `detect` entries, so
the layers under the engine (the store, the careers-page reader, the
closure prober, page capture) know every vendor host without naming one.
"""

from __future__ import annotations

import re
import sys
import tomllib
from collections.abc import Iterable
from pathlib import Path

from src.rows import JSON, dig
from src.rows import HandleColumn

from .paths import DATA_DIR

Spec = dict[str, JSON]

SPEC_DIR = Path(__file__).parent / "board_specs"
#: Where a compiled build reads spec overrides; None from source.
OVERRIDE_DIR = DATA_DIR / "boards" if "__compiled__" in globals() else None


def _read(path: Path) -> Spec:
    return tomllib.loads(path.read_text("utf-8"))


def load(spec_dir: Path, override_dir: Path | None) -> tuple[dict[str, Spec], dict[str, Spec]]:
    """(the specs in detection order, the bundled ones): `spec_dir`'s, in
    its `_order.toml` order, each replaced or followed by `override_dir`'s
    files (a name starting "_" is no spec). Each override is reported on
    stderr; one that does not parse is skipped."""
    order: list[str] = tomllib.loads((spec_dir / "_order.toml").read_text("utf-8"))["order"]
    bundled = {n: _read(spec_dir / f"{n}.toml") for n in order}
    boards = dict(bundled)
    found: list[Path] = (sorted(override_dir.glob("*.toml"))
                         if override_dir and override_dir.is_dir() else [])
    for path in (p for p in found if not p.stem.startswith("_")):
        try:
            boards[path.stem] = spec = _read(path)
        except (OSError, UnicodeError, tomllib.TOMLDecodeError) as e:
            print(f"[!] board override {path} skipped: {e}", file=sys.stderr)
            continue
        verb = ("adds a platform" if path.stem not in bundled
                else "is the bundled spec: delete it" if spec == bundled[path.stem]
                else "replaces the bundled spec")
        print(f"[i] board override {path} {verb}", file=sys.stderr)
    return boards, bundled


BOARDS, BUNDLED = load(SPEC_DIR, OVERRIDE_DIR)

#: The spec that reads a careers page itself, no ATS signature on it: the
#: sniffer's last resort, a board named by its URL alone.
CAREERS_PAGE_ATS = "custom"

#: The store columns naming a board whose spec sets no `handle.columns`:
#: the default of src.ats.board.spec.Handle, and the store's.
DEFAULT_HANDLE_COLUMNS: tuple[HandleColumn, ...] = ("slug",)

#: Job aggregators: hosts listing other employers' postings. A careers page
#: never names one as its own board, and they bot-gate anonymous reads, so
#: a probe there says nothing.
AGGREGATOR_HOSTS = ("linkedin.com", "indeed.com", "glassdoor.", "ziprecruiter.com",
                    "simplyhired.com", "monster.com", "dice.com", "builtin.com")


def _hosts(fetchable: bool) -> tuple[str, ...]:
    """The vendor hosts the specs' `detect` entries claim, in spec order;
    only a fetchable spec's (one with a `listing`) when `fetchable`. An
    override the engine refuses still counts: it parsed."""
    hosts: list[JSON] = []
    for s in BOARDS.values():
        dets = s.get("detect")
        if (s.get("listing") or not fetchable) and isinstance(dets, list):
            hosts += [dig(d, "host") for d in dets]
    return tuple(dict.fromkeys(h for h in hosts if isinstance(h, str)))


#: The vendor hosts of the platforms the engine fetches.
FETCHABLE_HOSTS = _hosts(fetchable=True)
#: Hosts shared by many employers: a page there names a board or a listing,
#: never the company that owns it, so it is no company's own careers page
#: or website: the aggregators, every ATS vendor host (fetchable or lead),
#: and Google's, which serve its search and many employers' Sites pages.
SHARED_HOSTS = AGGREGATOR_HOSTS + _hosts(fetchable=False) + ("google.com",)


def hosts_re(hosts: Iterable[str]) -> re.Pattern[str]:
    """A case-blind regex finding any of `hosts` (literal fragments) in a
    URL or host."""
    return re.compile("|".join(map(re.escape, hosts)), re.I)
