#!/usr/bin/env python3
"""Write src/config/boards/README.md, the board catalog, from the bundled specs.

    python tools/board_catalog.py           # rewrite the catalog
    python tools/board_catalog.py --check   # exit 1 when it is stale

The catalog is a view: a platform's row and notes come from its spec file
(the data, and the comment block that opens the file), so edit those and
rerun. A compiled build's overrides are not in it.
tests/test_board_specs.py::test_the_board_catalog_is_current fails on a
stale catalog.
"""

from __future__ import annotations

import argparse
import itertools
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from src import config                                      # noqa: E402
from src.ats.board import spec                              # noqa: E402
from src.ats.board.engine import Board                      # noqa: E402
from src.config.boards import SPEC_DIR                      # noqa: E402

CATALOG = ROOT / "src" / "config" / "boards" / "README.md"

HEADER = """\
# Board catalog

<!-- Generated by tools/board_catalog.py from src/config/boards/*.toml. Do not edit:
     change the spec, then run `python tools/board_catalog.py`. -->

Every ATS platform the crawler knows, in detection order: a URL or page two
specs both match goes to the earlier one (tests/test_board_specs.py
declares the overlaps). A **lead** is detected but not fetched. A key's
meaning is its description in `src/ats/board/spec.py`.

| # | Platform | Kind | Hosts | Listing | Closure | Flags | Canary |
|---:|---|---|---|---|---|---|---|
"""
FLAGS = ("sweep", "eager", "prunable", "guess")


def _cell(text: str) -> str:
    return text.replace("|", "\\|") or "—"


def _row(i: int, b: Board) -> str:
    s = b.spec
    listing = " → ".join(f"{alt.decoder.kind}{f' · {alt.pager.kind} pager' if alt.pager else ''}"
                         for alt in s.listing)
    cells = [str(i), f"`{b.name}`", "fetchable" if b.fetchable else "lead",
             " · ".join(d.host for d in s.detect if d.host) or ("page text" if s.detect else ""),
             listing, s.via if b.fetchable else "", " ".join(f for f in FLAGS if getattr(s, f)),
             s.canary.name if s.canary else ""]
    return "| " + " | ".join(map(_cell, cells)) + " |"


def _header(name: str) -> str:
    """The comment block that opens the spec's file, unmarked: the lines up
    to the first blank one (a comment touching a key explains that key)."""
    lines = (SPEC_DIR / f"{name}.toml").read_text("utf-8").splitlines() + [""]
    head = list(itertools.takewhile(lambda ln: ln.startswith("#"), lines))
    return "\n".join(ln[2:] for ln in head) if lines[len(head)] == "" else ""


def _section(b: Board) -> str:
    """The platform's header comment, and each workaround's `why`."""
    about, _, raw = _header(b.name).partition("Notes:")
    notes = " ".join(raw.split())
    whys = [f"- `{path.removesuffix('.why')}`: {value}" for path, value, given, _ in spec.walk(b.spec)
            if given and path.endswith("why") and isinstance(value, str)]
    parts = [about.strip(), notes and f"**Notes.** {notes}", "\n".join(whys)]
    body = "\n\n".join(p for p in parts if p)
    return f"### `{b.name}`\n\n{body}\n" if body else ""


def render() -> str:
    boards = [Board(name, raw) for name, raw in config.BUNDLED.items()]
    rows = "\n".join(_row(i, b) for i, b in enumerate(boards, 1))
    sections = "\n".join(s for s in map(_section, boards) if s)
    return f"{HEADER}{rows}\n\n## Notes and workarounds\n\n{sections}"


def main() -> int:
    ap = argparse.ArgumentParser(description="Write the board catalog from the specs")
    ap.add_argument("--check", action="store_true", help="exit 1 if the catalog is stale")
    text = render()
    if ap.parse_args().check:
        stale = not CATALOG.exists() or CATALOG.read_text("utf-8") != text
        print(f"{CATALOG.relative_to(ROOT)}: {'stale' if stale else 'current'}")
        return int(stale)
    CATALOG.write_text(text, "utf-8", newline="\n")
    print(f"wrote {CATALOG.relative_to(ROOT)} ({len(config.BUNDLED)} platforms)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
