#!/usr/bin/env python3
"""Write the board specs' generated files: src/config/boards/README.md, the
catalog, from the bundled specs, and board-spec.schema.json beside it, the
JSON Schema editors and `tombi lint` check a spec file against.

    python tools/board_catalog.py           # rewrite both
    python tools/board_catalog.py --check   # exit 1 when either is stale

Both are views. A platform's row and notes come from its spec file (the
data, and the comment block that opens the file); the schema comes from
src.ats.board.spec (`json_schema`). Edit those and rerun. A compiled
build's overrides are not in the catalog.
tests/test_board_specs.py::test_the_generated_board_files_are_current fails
on a stale one.
"""

from __future__ import annotations

import argparse
import itertools
import json
import sys
from collections.abc import Callable
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from src import config                                      # noqa: E402
from src.ats.board import spec                              # noqa: E402
from src.ats.board.engine import Board                      # noqa: E402
from src.config.boards import SPEC_DIR                      # noqa: E402

CATALOG = SPEC_DIR / "README.md"
SCHEMA = SPEC_DIR / "board-spec.schema.json"

HEADER = """\
# Board catalog

<!-- Generated by tools/board_catalog.py from src/config/boards/*.toml. Do not edit:
     change the spec, then run `python tools/board_catalog.py`. -->

Every ATS platform the crawler knows, in detection order: a URL or page two
specs both match goes to the earlier one (tests/test_board_specs.py
declares the overlaps). A **lead** is detected but not fetched. A key's
meaning is its description in `src/ats/board/spec.py`.

**Editing a spec.** Each `<name>.toml` here is one platform, and `_order.toml`
sets detection order. An editor with the Tombi extension completes and checks
a spec against `board-spec.schema.json` (associated in `tombi.toml`).
`tombi format src/config/boards` lays the files out, and
`tombi lint src/config/boards` checks them, as CI does. A compiled build also reads
`DATA_DIR/boards/<name>.toml` (on Windows `%LOCALAPPDATA%\\JobCrawler\\boards`):
a bundled name replaces that spec, and a new name adds a platform after the
last.

| # | Platform | Kind | Hosts | Listing | Closure | Flags | Canary |
|---:|---|---|---|---|---|---|---|
"""
FLAGS = ("sweep", "eager", "prunable", "guess")


def _cell(text: str) -> str:
    return text.replace("|", "\\|") or "—"


def _row(i: int, b: Board) -> str:
    s = b.spec
    listing = " → ".join(f"{alt.decoder.kind}{f' · {alt.pager.kind} pager' if alt.pager else ''}"
                         for alt in s.listing)
    cells = [str(i), f"`{b.name}`", "fetchable" if b.fetchable else "lead",
             " · ".join(d.host for d in s.detect if d.host) or ("page text" if s.detect else ""),
             listing, s.via if b.fetchable else "", " ".join(f for f in FLAGS if getattr(s, f)),
             s.canary.name if s.canary else ""]
    return "| " + " | ".join(map(_cell, cells)) + " |"


def _header(name: str) -> str:
    """The comment block that opens the spec's file, unmarked: the lines up
    to the first blank one (a comment touching a key explains that key)."""
    lines = (SPEC_DIR / f"{name}.toml").read_text("utf-8").splitlines() + [""]
    head = list(itertools.takewhile(lambda ln: ln.startswith("#"), lines))
    return "\n".join(ln[2:] for ln in head) if lines[len(head)] == "" else ""


def _section(b: Board) -> str:
    """The platform's header comment, and each workaround's `why`."""
    about, _, raw = _header(b.name).partition("Notes:")
    notes = " ".join(raw.split())
    whys = [f"- `{path.removesuffix('.why')}`: {value}" for path, value, given, _ in spec.walk(b.spec)
            if given and path.endswith("why") and isinstance(value, str)]
    parts = [about.strip(), notes and f"**Notes.** {notes}", "\n".join(whys)]
    body = "\n\n".join(p for p in parts if p)
    return f"### `{b.name}`\n\n{body}\n" if body else ""


def render() -> str:
    boards = [Board(name, raw) for name, raw in config.BUNDLED.items()]
    rows = "\n".join(_row(i, b) for i, b in enumerate(boards, 1))
    sections = "\n".join(s for s in map(_section, boards) if s)
    return f"{HEADER}{rows}\n\n## Notes and workarounds\n\n{sections}"


def schema() -> str:
    return json.dumps(spec.json_schema(), indent=2, ensure_ascii=False) + "\n"


#: Each generated file and what renders it.
GENERATED: dict[Path, Callable[[], str]] = {CATALOG: render, SCHEMA: schema}


def main() -> int:
    ap = argparse.ArgumentParser(description="Write the board catalog and spec schema")
    ap.add_argument("--check", action="store_true", help="exit 1 if either is stale")
    check, stale = ap.parse_args().check, 0
    for path, make in GENERATED.items():
        text, name = make(), path.relative_to(ROOT)
        if check:
            bad = not path.exists() or path.read_text("utf-8") != text
            stale += bad
            print(f"{name}: {'stale' if bad else 'current'}")
        else:
            path.write_text(text, "utf-8", newline="\n")
            print(f"wrote {name}")
    return int(bool(stale))


if __name__ == "__main__":
    sys.exit(main())
